In [12]:
import torch
import torch.nn as nn
import numpy as np

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(5)


In [20]:
x = torch.arange(10).float()
def merge(tensor, indexA, indexB):
    print(x)
    print(x[indexB])
    y = x
    print(y)
    y = x[x!=x[indexB]]
    print(y)
    y[indexA]+=x[indexB]
    y[indexA]/=2.0
    print(y)
merge(x, 4, 5)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor(5.)
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0., 1., 2., 3., 4., 6., 7., 8., 9.])
tensor([0.0000, 1.0000, 2.0000, 3.0000, 4.5000, 6.0000, 7.0000, 8.0000, 9.0000])
